import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import Head from "next/head";
import "@public/css/bootstrap.min.css";
import "@public/css/style.css";
import "@public/css/responsive.css";

import Script from "next/script";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "HomeHarbor",
  description: "Generated by create next app"
};

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"]
});

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/images/favicon.html" />
      </Head>
      <body className={nunito.className}>
        <Header />

        {children}
        <Footer />
        <Script src="/js/jquery-3.3.1.js" />
        <Script src="/js/popper.min.js" />
        <Script src="/js/bootstrap.min.js" />
        <Script src="/js/jquery.mmenu.all.js" />
        <Script src="/js/ace-responsive-menu.js" />
        <Script src="/js/jquery-migrate-3.0.0.min.js" />
        <Script src="/js/bootstrap-select.min.js" />
        <Script src="/js/isotop.js" />
        <Script src="/js/snackbar.min.js" />
        <Script src="/js/simplebar.js" />
        <Script src="/js/parallax.js" />
        <Script src="/js/scrollto.js" />
        <Script src="/js/jquery-scrolltofixed-min.js" />
        <Script src="/js/jquery.counterup.js" />
        <Script src="/js/wow.min.js" />
        <Script src="/js/slider.js" />
        <Script src="/js/pricing-slider.js" />
        <Script src="/js/timepicker.js" />
        <Script src="/js/google-maps.js" />
        <Script src="/js/script.js" />
      </body>
    </html>
  );
}
